# Change yourself for your user_input data
countdata: "data/user_input/rxn-cpm-named.tsv"
metadata: "data/user_input/sampleinfo.txt"
baseline: "T0"

# Amount of threads for running limma in parallel with BiocParallel
limma_threads: 2

# Params for Maaslin2
transformation: "LOG" # LOG, LOGIT, AST, NONE
analysis_method: "LM" # LM, CPLM

# Top N for bubbleplot
top: 40